Repository paritytech/parity-wasm, pull requests merged in 2021-07, with the labels that each got.

#308 Replace travis with github actions
  .github/workflows/check.yml
  .travis.yml
Labels: A0-pleasereview

#307 Fix linting issues related to the simd macro
  src/elements/ops.rs
Labels: A0-pleasereview, F6-refactor

#309 Update dev dependency
  Cargo.toml
Labels: A0-pleasereview, A2-insubstantial

#305 Cleanup
  examples/bench-decoder.rs
  examples/data.rs
  examples/exports.rs
  examples/info.rs
  examples/inject.rs
  examples/show.rs
  src/builder/code.rs
  src/builder/data.rs
  src/builder/export.rs
  src/builder/global.rs
  src/builder/import.rs
  src/builder/memory.rs
  src/builder/misc.rs
  src/builder/module.rs
  src/builder/table.rs
  src/elements/export_entry.rs
  src/elements/func.rs
  src/elements/global_entry.rs
  src/elements/import_entry.rs
  src/elements/index_map.rs
  src/elements/module.rs
  src/elements/name_section.rs
  src/elements/ops.rs
  src/elements/primitives.rs
  src/elements/reloc_section.rs
  src/elements/section.rs
  src/elements/segment.rs
Labels: A0-pleasereview, F6-refactor

#306 Cleanup / Compat. breaking
  Cargo.toml
  src/io.rs
Labels: A0-pleasereview, F6-refactor

#310 Fix last linting issues
  examples/bench-decoder.rs
  src/elements/index_map.rs
  src/elements/module.rs
Labels: A0-pleasereview, A2-insubstantial

#311 Add rustfmt
  .github/workflows/check.yml
  examples/bench-decoder.rs
  examples/build.rs
  examples/data.rs
  examples/exports.rs
  examples/info.rs
  examples/inject.rs
  examples/roundtrip.rs
  examples/show.rs
  justfile
  rustfmt.toml
  src/builder/code.rs
  src/builder/data.rs
  src/builder/export.rs
  src/builder/global.rs
  src/builder/import.rs
  src/builder/invoke.rs
  src/builder/memory.rs
  src/builder/misc.rs
  src/builder/mod.rs
  src/builder/module.rs
  src/builder/table.rs
  src/elements/export_entry.rs
  src/elements/func.rs
  src/elements/global_entry.rs
  src/elements/import_entry.rs
  src/elements/index_map.rs
  src/elements/mod.rs
  src/elements/module.rs
  src/elements/name_section.rs
  src/elements/ops.rs
  src/elements/primitives.rs
  src/elements/reloc_section.rs
  src/elements/section.rs
  src/elements/segment.rs
  src/elements/types.rs
  src/io.rs
  src/lib.rs
Labels: A0-pleasereview
